# flake8: noqa

"""
    Copyright 2023 Calcasa B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Calcasa Public API v1

    The version of the OpenAPI document: 1.3.0
    Contact: info@calcasa.nl
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.3.0"

# import ApiClient
from calcasa.api.api_client import ApiClient

# import Configuration
from calcasa.api.configuration import Configuration

# import exceptions
from calcasa.api.exceptions import OpenApiException
from calcasa.api.exceptions import ApiAttributeError
from calcasa.api.exceptions import ApiTypeError
from calcasa.api.exceptions import ApiValueError
from calcasa.api.exceptions import ApiKeyError
from calcasa.api.exceptions import ApiException
