# coding: utf-8

"""
Copyright 2026 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from calcasa.api.models.file_info import FileInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class FileSet(BaseModel):
    """
    FileSet
    """  # noqa: E501

    id: UUID = Field(
        description="The file set ID, which is a unique identifier for the file set. This ID is used to track and manage the file set throughout its lifecycle. It is generated by the system when the file set is created and is used in API requests to reference the specific file set."
    )
    files: Optional[List[FileInfo]] = Field(
        default=None, description="The files associated with the file set."
    )
    created_on: datetime = Field(
        alias="createdOn", json_schema_extra={"examples": ["2021-04-28T12:34:45Z"]}
    )
    expires_after: Optional[datetime] = Field(
        default=None,
        description="If specified, the file set will expire after this date and time. If no appropriate action is taken before this date and time, the file set and all its contents will be deleted.",
        alias="expiresAfter",
        json_schema_extra={"examples": ["2021-04-28T12:34:45Z"]},
    )
    modified_on: datetime = Field(
        alias="modifiedOn", json_schema_extra={"examples": ["2021-04-28T12:34:45Z"]}
    )
    type: StrictStr = Field(
        description="The type of the file set. This value should be constant for a given type of file set and should be agreed upon with Calcasa before use. It is used to ensure that the correct processing logic is applied to the file set based on its intended purpose.  The tuple type, revision and period should always be unique."
    )
    revision: StrictInt = Field(
        description="A revision number for the file set that is incremented for every retry or redelivery. The tuple type, revision and period should always be unique."
    )
    period: Optional[date] = Field(
        default=None,
        description="The period of the inbound file set. This is a string that represents the time period for which the file set is relevant. It is used to categorize and identify the time frame of the data contained in the file set. The first day of the period is used when the period is a year, quarter or month. For example use the first of April for Q2. The period is represented in the format YYYY-MM-DD, where YYYY is the year, MM is the month, and DD is the day. If the period is not applicable, it can be set to null, only do this after consulting with Calcasa. The tuple type, revision and period should always be unique.",
        json_schema_extra={"examples": ["2021-04-28"]},
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "files",
        "createdOn",
        "expiresAfter",
        "modifiedOn",
        "type",
        "revision",
        "period",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "id",
                "created_on",
                "expires_after",
                "modified_on",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict["files"] = _items
        # set to None if files (nullable) is None
        # and model_fields_set contains the field
        if self.files is None and "files" in self.model_fields_set:
            _dict["files"] = None

        # set to None if expires_after (nullable) is None
        # and model_fields_set contains the field
        if self.expires_after is None and "expires_after" in self.model_fields_set:
            _dict["expiresAfter"] = None

        # set to None if period (nullable) is None
        # and model_fields_set contains the field
        if self.period is None and "period" in self.model_fields_set:
            _dict["period"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "files": (
                    [FileInfo.from_dict(_item) for _item in obj["files"]]
                    if obj.get("files") is not None
                    else None
                ),
                "createdOn": obj.get("createdOn"),
                "expiresAfter": obj.get("expiresAfter"),
                "modifiedOn": obj.get("modifiedOn"),
                "type": obj.get("type"),
                "revision": obj.get("revision"),
                "period": obj.get("period"),
            }
        )
        return _obj
