# coding: utf-8

"""
Copyright 2026 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class FileSetLimits(BaseModel):
    """
    FileSetLimits
    """  # noqa: E501

    inbound_max_total_size_in_kilo_bytes: StrictInt = Field(
        description="The maximum total size of all files in an inbound file set, in kilobytes (1000 bytes). This limit ensures that the combined size of all files within a file set does not exceed a certain threshold, which helps manage storage and processing resources.",
        alias="inboundMaxTotalSizeInKiloBytes",
    )
    inbound_max_file_size_in_kilo_bytes: StrictInt = Field(
        description="The maximum size of a single file in an inbound file set, in kilobytes (1000 bytes). This limit ensures that individual files do not exceed a certain size, which helps manage storage and processing resources.",
        alias="inboundMaxFileSizeInKiloBytes",
    )
    inbound_max_compressed_chunk_size_in_kilo_bytes: StrictInt = Field(
        description="The maximum size of a compressed chunk in an inbound file set, in kilobytes (1000 bytes). This limit ensures that individual compressed chunks do not exceed a certain size, which helps manage storage and processing resources.",
        alias="inboundMaxCompressedChunkSizeInKiloBytes",
    )
    inbound_max_total_files: StrictInt = Field(
        description="The maximum number of files in an inbound file set. This limit ensures that the number of files within a file set does not exceed a certain threshold, which helps manage storage and processing resources.",
        alias="inboundMaxTotalFiles",
    )
    inbound_ttl_in_seconds: StrictInt = Field(
        description="The time-to-live (TTL) for inbound file sets, in seconds. This value indicates how long an inbound file set will remain valid before it expires and is deleted if it is not confirmed. It helps manage the lifecycle of inbound file sets and ensures that they are processed within a certain timeframe.",
        alias="inboundTtlInSeconds",
    )
    outbound_ttl_in_seconds: StrictInt = Field(
        description="The time-to-live (TTL) for outbound file sets, in seconds. This value indicates how long an outbound file set will remain valid before it expires and is deleted if it is not downloaded. It helps manage the lifecycle of outbound file sets and ensures that they are processed within a certain timeframe.",
        alias="outboundTtlInSeconds",
    )
    __properties: ClassVar[List[str]] = [
        "inboundMaxTotalSizeInKiloBytes",
        "inboundMaxFileSizeInKiloBytes",
        "inboundMaxCompressedChunkSizeInKiloBytes",
        "inboundMaxTotalFiles",
        "inboundTtlInSeconds",
        "outboundTtlInSeconds",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileSetLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileSetLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "inboundMaxTotalSizeInKiloBytes": obj.get(
                    "inboundMaxTotalSizeInKiloBytes"
                ),
                "inboundMaxFileSizeInKiloBytes": obj.get(
                    "inboundMaxFileSizeInKiloBytes"
                ),
                "inboundMaxCompressedChunkSizeInKiloBytes": obj.get(
                    "inboundMaxCompressedChunkSizeInKiloBytes"
                ),
                "inboundMaxTotalFiles": obj.get("inboundMaxTotalFiles"),
                "inboundTtlInSeconds": obj.get("inboundTtlInSeconds"),
                "outboundTtlInSeconds": obj.get("outboundTtlInSeconds"),
            }
        )
        return _obj
