# coding: utf-8

"""
Copyright 2025 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FunderingSoortBron(str, Enum):
    """
    Bron voor funderingsinformatie. | Waarde | Omschrijving | | --- | --- | | `onbekend` | Onbekende bron. | | `model` | Modelmatig. | | `document` | Uit een document. | | `bouweenheid` | Op basis van woningen in hetzelfde woonblok. |
    """

    """
    allowed enum values
    """
    ONBEKEND = "onbekend"
    MODEL = "model"
    DOCUMENT = "document"
    BOUWEENHEID = "bouweenheid"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FunderingSoortBron from a JSON string"""
        return cls(json.loads(json_str))
