# coding: utf-8

"""
Copyright 2026 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from calcasa.api.models.compression_type import CompressionType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python


class InboundFileInfo(BaseModel):
    """
    InboundFileInfo
    """  # noqa: E501

    index: StrictInt = Field(
        description="The index of the file within the file set. Zero-based."
    )
    name: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(
        description="The name of the file, including its extension. This needs to be unique within the file set.  This can contain '/' as the directory separator, but the file name cannot start or end with a '/' and cannot contain consecutive '/' characters. Can contain A-Z, a-z, 0-9, a space and '-./{}[]()' characters. The maximum length is 128 characters.",
        json_schema_extra={"examples": ["data.csv"]},
    )
    content_hash: Annotated[str, Field(strict=True)] = Field(
        description="The SHA256 hash of the file contents, represented as an uppercase hexadecimal string. For the outbound file sets this is the expected hash, for inbound file sets this is the actual hash of the file contents.",
        alias="contentHash",
        json_schema_extra={
            "examples": [
                "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"
            ]
        },
    )
    size: StrictInt = Field(
        description="The file size in bytes. For the outbound file sets this is the expected size, for inbound file sets this is the actual size of the file contents."
    )
    content_type: StrictStr = Field(
        description='The content type of the file, which indicates the media type of the file contents. This is used to determine how to handle and process the file. For example, "application/pdf" for PDF files, "image/jpeg" for JPEG images, etc. Refer to [IANA Media Types](https://www.iana.org/assignments/media-types/media-types.xhtml) for possible values.',
        alias="contentType",
    )
    compression: Optional[CompressionType] = Field(
        default=None,
        description='The compression algorithm used for the file. This only applied to inboud files. All chunks will be concatenated and then decompressed. The compression type is used to determine how the file contents are processed and stored. It is important to specify the correct compression type to ensure that the file can be properly decompressed and read. The compression type is optional and defaults to "none" if not specified.',
    )
    __properties: ClassVar[List[str]] = [
        "index",
        "name",
        "contentHash",
        "size",
        "contentType",
        "compression",
    ]

    @field_validator("name")
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-Za-z0-9-_\.\[\]\{\}\(\)\/ ]+$", value):
            raise ValueError(
                r"must validate the regular expression /^[A-Za-z0-9-_\.\[\]\{\}\(\)\/ ]+$/"
            )
        return value

    @field_validator("content_hash")
    def content_hash_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not isinstance(value, str):
            value = str(value)

        if not re.match(r"^[A-F0-9]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[A-F0-9]{64}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InboundFileInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InboundFileInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "index": obj.get("index"),
                "name": obj.get("name"),
                "contentHash": obj.get("contentHash"),
                "size": obj.get("size"),
                "contentType": obj.get("contentType"),
                "compression": obj.get("compression"),
            }
        )
        return _obj
