# coding: utf-8

"""
Copyright 2026 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InboundFileSetState(str, Enum):
    """
    Inbound file set states.  | Value | Description | | --- | --- | | `created` | File set has just been created and is waiting for the files to be uploaded. | | `uploading` | File set is being uploaded, but not all files have been uploaded yet. | | `verifying` | File set has been fully uploaded and has been confirmed, the file set is in the process of being verified. | | `accepted` | File set has been fully uploaded and has been confirmed, the file set has been verified and is ready for processing. | | `accepted_with_warnings` | File set has been fully uploaded and has been confirmed, the file set has been verified and is ready for processing, but there were some warnings during the verification process. | | `rejected` | File set has been fully uploaded and has been confirmed, but the file set has been rejected during the verification process. There will be errors in the file set that need to be fixed before it can be processed. | | `expired` | File set has expired and all its uploaded contents have been deleted. |
    """

    """
    allowed enum values
    """
    CREATED = "created"
    UPLOADING = "uploading"
    VERIFYING = "verifying"
    ACCEPTED = "accepted"
    ACCEPTED_WITH_WARNINGS = "accepted_with_warnings"
    REJECTED = "rejected"
    EXPIRED = "expired"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InboundFileSetState from a JSON string"""
        return cls(json.loads(json_str))
