# coding: utf-8

"""
Copyright 2025 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from calcasa.api.models.taxatiestatus import Taxatiestatus
from typing import Optional, Set
from typing_extensions import Self


class Taxatiedata(BaseModel):
    """
    Taxatiedata
    """  # noqa: E501

    taxatieorganisatie: Optional[StrictStr] = Field(
        default=None,
        description="De interne naam van de taxatieorganisatie. Deze wijzigt niet.",
    )
    taxatieorganisatie_weergave: Optional[StrictStr] = Field(
        default=None,
        description="De externe of rapport naam van de taxatieorganisatie.",
        alias="taxatieorganisatieWeergave",
    )
    taxateurnaam: Optional[StrictStr] = Field(
        default=None,
        description="De naam van de taxateur die de waardering heeft behandeld.",
    )
    status: Optional[Taxatiestatus] = None
    taxatiedatum: Optional[datetime] = Field(
        default=None,
        description="De datum/tijd waarop de waardering getaxeerd is, in UTC.",
    )
    __properties: ClassVar[List[str]] = [
        "taxatieorganisatie",
        "taxatieorganisatieWeergave",
        "taxateurnaam",
        "status",
        "taxatiedatum",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Taxatiedata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Taxatiedata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "taxatieorganisatie": obj.get("taxatieorganisatie"),
                "taxatieorganisatieWeergave": obj.get("taxatieorganisatieWeergave"),
                "taxateurnaam": obj.get("taxateurnaam"),
                "status": obj.get("status"),
                "taxatiedatum": obj.get("taxatiedatum"),
            }
        )
        return _obj
