# coding: utf-8

"""
Copyright 2025 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class VerkoopBijzonderheden(str, Enum):
    """
    | Waarde | Omschrijving | | --- | --- | | `onbekend` | Bijzonderheden onbekend. | | `executieverkoop` | Een indicatie dat het object is verkocht via een executieveiling. | | `familieverkoop` | Een indicatie dat de transactie is geregistreerd als familieverkoop. | | `meerOnroerendGoed` | Een indicatie dat de transactie meerdere percelen bevat. | | `zittendeHuurder` | Een indicatie dat de transactie is geregistreerd als verkoop aan de zittende huurder. | | `verkoperNietNatuurlijk` | Een indicatie dat de verkoper een niet-natuurlijke persoon is. | | `koperNietNatuurlijk` | Een indicatie dat de koper een niet-natuurlijke persoon is. | | `nietWoning` | Een indicatie dat het object geregistreerd is als niet-woning. | | `erfdienstbaarheid` | Een indicatie dat er een erfdienstbaarheid op het object gevestigd is. |
    """

    """
    allowed enum values
    """
    ONBEKEND = "onbekend"
    EXECUTIEVERKOOP = "executieverkoop"
    FAMILIEVERKOOP = "familieverkoop"
    MEERONROERENDGOED = "meerOnroerendGoed"
    ZITTENDEHUURDER = "zittendeHuurder"
    VERKOPERNIETNATUURLIJK = "verkoperNietNatuurlijk"
    KOPERNIETNATUURLIJK = "koperNietNatuurlijk"
    NIETWONING = "nietWoning"
    ERFDIENSTBAARHEID = "erfdienstbaarheid"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VerkoopBijzonderheden from a JSON string"""
        return cls(json.loads(json_str))
