# coding: utf-8

"""
Copyright 2025 Calcasa B.V.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Calcasa Public API
The Calcasa API is used to connect to Calcasa provided services. For more information, please visit [Documentation](https://docs.calcasa.nl) or [GitHub](https://github.com/calcasa/api).

Contact: info@calcasa.nl
Generated by: https://openapi-generator.tech
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from calcasa.api.models.aanvraagdoel import Aanvraagdoel
from calcasa.api.models.product_type import ProductType
from calcasa.api.models.waardering_status import WaarderingStatus
from typing import Optional, Set
from typing_extensions import Self


class WaarderingZoekParameters(BaseModel):
    """
    WaarderingZoekParameters
    """  # noqa: E501

    aangemaakt: Optional[datetime] = Field(
        default=None,
        description="De datum/tijd waarop de waardering is aangemaakt, in UTC.",
    )
    geldverstrekker: Optional[StrictStr] = Field(
        default=None, description="De naam van de geldverstrekker voor de waardering."
    )
    product_type: ProductType = Field(alias="productType")
    aanvraagdoel: Optional[Aanvraagdoel] = None
    waardering_status: Optional[WaarderingStatus] = Field(
        default=None, alias="waarderingStatus"
    )
    bag_nummeraanduiding_id: StrictInt = Field(
        description="Verplicht.", alias="bagNummeraanduidingId"
    )
    __properties: ClassVar[List[str]] = [
        "aangemaakt",
        "geldverstrekker",
        "productType",
        "aanvraagdoel",
        "waarderingStatus",
        "bagNummeraanduidingId",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WaarderingZoekParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if aangemaakt (nullable) is None
        # and model_fields_set contains the field
        if self.aangemaakt is None and "aangemaakt" in self.model_fields_set:
            _dict["aangemaakt"] = None

        # set to None if geldverstrekker (nullable) is None
        # and model_fields_set contains the field
        if self.geldverstrekker is None and "geldverstrekker" in self.model_fields_set:
            _dict["geldverstrekker"] = None

        # set to None if aanvraagdoel (nullable) is None
        # and model_fields_set contains the field
        if self.aanvraagdoel is None and "aanvraagdoel" in self.model_fields_set:
            _dict["aanvraagdoel"] = None

        # set to None if waardering_status (nullable) is None
        # and model_fields_set contains the field
        if (
            self.waardering_status is None
            and "waardering_status" in self.model_fields_set
        ):
            _dict["waarderingStatus"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WaarderingZoekParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "aangemaakt": obj.get("aangemaakt"),
                "geldverstrekker": obj.get("geldverstrekker"),
                "productType": obj.get("productType"),
                "aanvraagdoel": obj.get("aanvraagdoel"),
                "waarderingStatus": obj.get("waarderingStatus"),
                "bagNummeraanduidingId": obj.get("bagNummeraanduidingId"),
            }
        )
        return _obj
